version: '3'

services:
  storybook:
    build:
      context: "./app"
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./app/storybook:/app/storybook:cached
