version: '3'

services:
  storybook:
    build:
      context: "./"
      dockerfile: "Dockerfile.storybook"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./storybook:/app/storybook:cached
