version: 2
jobs:
  build-storybook:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/vue-storybook-ts
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Install node modules
          command: |
            npm install
      - run:
          name: Generate Storybook
          command: |
            npm run storybook:build
      - store_artifacts:
          path: ./storybook
          destination: ~/storybook
workflows:
  version: 2
  build:
    jobs:
      - build-storybook
  # build:
  #   docker:
  #     - image: google/cloud-sdk
  #   working_directory: /home/vue-storybook-ts
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 18.06.0-ce
  #     - run:
  #         name: Setup cloud SDK
  #         command: |
  #           echo $GCLOUD_SERVICE_KEY | base64 --decode > /home/gcloud-service-key.json
  #           gcloud auth activate-service-account --key-file /home/gcloud-service-key.json
  #           gcloud --quiet config set project $PROJECT_ID
  #           gcloud --quiet config set compute/zone us-west1-a
  #           gcloud --quiet auth configure-docker
  #     - run:
  #         name: Push docker image
  #         command: |
  #           docker build -t storybook -f Dockerfile.storybook .
  #           LATEST_TAG=gcr.io/$PROJECT_ID/storybook:latest
  #           docker tag storybook $LATEST_TAG
  #           docker push $LATEST_TAG
