version: 2
jobs:
  build-storybook:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/vue-storybook-ts
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
            - v1-
          paths:
            - /cache/modules.tar
      - run:
          name: Install node modules
          command: |
            npm install
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths: /cache/modules.tar
      - run:
          name: Generate Storybook
          command: |
            npm run storybook:build
      - store_artifacts:
          path: ./storybook
          destination: ~/storybook
  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      CLUSTER_NAME: prod-cluster-1
      ZONE: us-west1-a
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > /home/gcloud-service-key.json
            gcloud auth activate-service-account --key-file /home/gcloud-service-key.json
            gcloud --quiet config set project $PROJECT_ID
            gcloud --quiet config set compute/zone $ZONE
            gcloud --quiet auth configure-docker
            gcloud container clusters get-credentials $CLUSTER_NAME
      - run:
          name: Push Docker image
          command: |
            docker build -t app .
            LATEST_TAG=gcr.io/$PROJECT_ID/app:$CIRCLE_SHA1
            docker tag app $LATEST_TAG
            docker push $LATEST_TAG
      - run:
          name: Deploy App to Kubernetes
          command: |
            kubectl apply -f .kubernetes/deployment.yml
            kubectl apply -f .kubernetes/service.yml
            kubectl apply -f .kubernetes/ingress.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-storybook
      - deploy
