version: 2.1
orbs:
  gke: circleci/gcp-gke@0.2.0
  gcr: circleci/gcp-gcr@0.6.1
jobs:
  build-storybook:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/vue-storybook-ts
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - /cache/modules.tar
      - run:
          name: Install node modules
          command: |
            npm install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths: /cache/modules.tar
      - run:
          name: Generate Storybook
          command: |
            npm run storybook:build
      - store_artifacts:
          path: ./storybook
      - run:
          name: Notify Artifact to PR
          command: |
            npm run moxci

  build-push-image:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: app
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: app
          tag: $CIRCLE_SHA1

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    environment:
        CLUSTER_NAME: circle-ci-cluster
    steps:
      - gke/install
      - gke/init
      - gke/rollout-image:
          cluster: $CLUSTER_NAME
          deployment: web-deployment
          container: web
          image: gcr.io/$GOOGLE_PROJECT_ID/app:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-storybook
      - build-push-image:
          filters:
             branches:
               only: master
      - deploy:
          requires:
            - build-push-image
          filters:
              branches:
                  only: master
