version: 2.1
orbs:
  node: circleci/node@1.0.1
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build-storybook:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/vue-storybook-ts
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
            - v1-
          paths:
            - /cache/modules.tar
      - run:
          name: Install node modules
          command: |
            npm install
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths: /cache/modules.tar
      - run:
          name: Generate Storybook
          command: |
            npm run storybook:build
      - store_artifacts:
          path: ./storybook
          destination: ~/storybook

  build-push-image:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - gcr/build-image:
          image: app
          tag: $CIRCLE_SHA1
      - gcr/push-image:
          image: app
          tag: $CIRCLE_SHA1

  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    environment:
        CLUSTER_NAME: circle-ci-cluster
        ZONE: us-west1-a
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          deployment: $CLUSTER_NAME
          container: vue-storybook-ts-web
          image: gcr.io/$GOOGLE_PROJECT_ID/app:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-storybook
      - build-push-image:
        filters:
           branches:
             only: master
      - deploy:
        requires:
          - build-push-image
        filters:
           branches:
             only: master
