apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: sampleapp.example.com
      http:
        paths:
          - backend:
              serviceName: web-service
              servicePort: 8080
